services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3080:3080"
    restart: unless-stopped
    environment:
      - CADDY_API=http://host.docker.internal:2019
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/caddy/Caddyfile:/app/Caddyfile
      - /etc/caddy/Caddyfile.custom:/app/Caddyfile.custom:ro
      - sites_data:/app/data

volumes:
  sites_data:
